Repository centfinance/Symmetric.ExchangeUI, pull requests merged in 2021-06, with the labels that each got.

#7 Various changes for xDai, Celo and Alfajores support
  package-lock.json
  package.json
  src/abi/Wxdai.json
  src/api/ethereum.ts
  src/assets/registry.xdai.json
  src/components/Header.vue
  src/components/swap/Button.vue
  src/config/alfajores.json
  src/config/celo.json
  src/config/index.ts
  src/config/kovan.json
  src/config/xdai.json
  src/pages/Swap.vue
  src/utils/helpers.ts
  src/utils/list.ts
  src/utils/provider.ts
  src/utils/storage.ts
  src/web3/helper.ts
Labels: bug, enhancement

#6 UI-Updates
  public/index.html
  src/App.vue
  src/components/Button.vue
  src/components/Header.vue
  src/components/ModalBase.vue
Labels: UI

#16 UI changes
  src/assets/registry.xdai.json
  src/assets/symmetric-logo.jpg
  src/assets/symmetric.png
  src/assets/symmetricIcon.svg
  src/components/Header.vue
Labels: UI

#19 Correction to WXDAI address in xDai config file
  package-lock.json
  src/config/xdai.json
Labels: bug
