Repository centfinance/Symmetric.ExchangeUI, pull requests merged in 2021-07, with the labels that each got.

#21 Update support for Sokol, Celo and Alfajores
  package-lock.json
  package.json
  src/abi/ERC20.json
  src/api/ethereum.ts
  src/components/Header.vue
  src/components/ModalAccount.vue
  src/components/swap/Button.vue
  src/components/swap/Routing.vue
  src/config/alfajores.json
  src/config/celo.json
  src/config/homestead.json
  src/config/index.ts
  src/config/kovan.json
  src/config/sokol.json
  src/config/xdai.json
  src/pages/Swap.vue
  src/utils/helpers.ts
  src/utils/list.ts
  src/utils/provider.ts
  src/utils/storage.ts
  src/web3/helper.ts
  src/web3/swapper.ts
Labels: enhancement

#22 Network info moved to new location
  src/components/Header.vue
  src/pages/Swap.vue
Labels: UI

#27 Fix to WalletConnect URL and default icons for non-Ethereum builds
  package.json
  src/components/Header.vue
  src/components/swap/Routing.vue
  src/config/xdai.json
  src/pages/Swap.vue
  src/utils/list.ts
  src/web3/swapper.ts
Labels: bug
